"""Offline handlers for the control agents: prompt optimizer and planner."""

from __future__ import annotations

import re

from app.core.text import keywords, split_sentences, strip_accents, truncate
from app.llm.providers.offline import OfflineReply
from app.llm.providers.offline.common import (
    clauses,
    detect_intents,
    is_french,
    read_context,
    reply_json,
)
from app.llm.types import LLMRequest
from app.schemas.agent import SupervisorChoice
from app.schemas.plan import Plan, PlanStep, StepType
from app.schemas.spec import Feasibility, PromptSpec

_DELIVERABLES = {
    "knowledge": "Summary of the relevant internal documentation, with citations",
    "research": "Research findings backed by evidence",
    "data": "Data analysis with key metrics",
    "coding": "Implementation proposal: components, API endpoints, data model, tests",
}
_CRITERIA = {
    "knowledge": "Statements based on internal documents cite their sources ([S1], [S2]...)",
    "research": "Findings are supported by evidence or sources",
    "data": "Key metrics are computed from platform data",
    "coding": "The proposal specifies components, API endpoints and the data model",
}
_NEED_MARKER = re.compile(r"^Cover the (knowledge|research|data|coding) aspect")
_DESIGN_VERBS = re.compile(
    r"\b(implement|developp|develop|coder|build|construi|concevoir|design|architect)"
)

# Request verbs and fillers that say nothing about the topic (kept out of the criteria).
_GENERIC_WORDS = frozenset(
    {
        "analyse",
        "analyser",
        "analyze",
        "propose",
        "proposer",
        "fais",
        "faire",
        "donne",
        "veux",
        "voudrais",
        "want",
        "need",
        "please",
        "merci",
        "disponibles",
        "available",
        "existing",
        "existants",
        "ajouter",
        "add",
        "create",
        "créer",
        "prépare",
        "prepare",
        "help",
        "aide",
        "aider",
        "make",
        "write",
        "écris",
    }
)

_RISKS = {
    "knowledge": "Internal documents may be incomplete or outdated",
    "research": "Available evidence may be partial",
    "data": "Platform data may be too sparse to support conclusions",
    "coding": "Schema changes and tenant isolation must be handled carefully",
}


def handle_prompt_optimizer(request: LLMRequest) -> OfflineReply:
    context = read_context(request)
    text: str = context["user_request"]
    intents = detect_intents(text)
    if text.rstrip().endswith("?") and "data" not in intents:
        # A question is an information request, answered from the knowledge base first; it only
        # asks for a design when it says so ("comment implémenter...", "how to build...").
        asks_for_design = _DESIGN_VERBS.search(strip_accents(text.lower()))
        intents = {"knowledge"} | ({"coding"} if asks_for_design else set())
    intents = intents or {"research"}
    words = [word for word in keywords(text) if word not in _GENERIC_WORDS]
    sentences = split_sentences(text)
    objective = truncate(sentences[0] if sentences else text, 300)
    if len(objective) < 10:
        objective = f"Address the request: {objective}"
    vague = len(words) < 5

    requirements = clauses(text) or [truncate(text, 300)]
    requirements += [f"Cover the {intent} aspect of the request" for intent in sorted(intents)]
    criteria = [f"The answer explicitly addresses: {', '.join(words[:5])}"] if words else []
    criteria += [_CRITERIA[intent] for intent in sorted(intents)]
    if "coding" in intents:
        criteria.append("Security and multi-tenant data isolation risks are addressed")

    spec = PromptSpec(
        objective=objective,
        context=(
            f"Request language: {'French' if is_french(text) else 'English'}. "
            f"Detected needs: {', '.join(sorted(intents))}. "
            "Generated by the offline simulator (rule-based, no LLM)."
        ),
        constraints=["Use only information available to the platform; do not invent facts"],
        requirements=[truncate(item, 300) for item in requirements[:12]],
        deliverables=[_DELIVERABLES[intent] for intent in sorted(intents)],
        risks=[_RISKS[intent] for intent in sorted(intents)],
        acceptance_criteria=criteria[:8],
        assumptions=["Scope limited to a first, production-ready iteration"]
        + (["The request is short: the most common interpretation is assumed"] if vague else []),
        clarifying_questions=(
            [
                "Which users and workflows are in scope?",
                "Which constraints (deadline, stack, budget) apply?",
            ]
            if vague
            else []
        ),
        needs_knowledge_base="knowledge" in intents,
        feasibility=Feasibility.NEEDS_CLARIFICATION if vague else Feasibility.ACTIONABLE,
    )
    return reply_json(spec)


def handle_supervisor(request: LLMRequest) -> OfflineReply:
    """Pick the highest-priority ready step (the policy validates the choice anyway)."""
    context = read_context(request)
    ready = sorted(context["ready_steps"], key=lambda step: step["priority"])
    step = ready[0]
    agent = (
        step["recommended_agent"]
        if step["recommended_agent"] in step["capable_agents"]
        else step["capable_agents"][0]
    )
    feedback = step.get("feedback") or []
    instructions = (
        "Address the reviewer feedback first: " + "; ".join(feedback)
        if feedback
        else f"Complete '{step['title']}' and keep the output concise and sourced."
    )
    choice = SupervisorChoice(
        step_id=step["id"],
        agent=agent,
        reason=f"highest priority among {len(ready)} ready step(s)",
        instructions=truncate(instructions, 1000),
    )
    return reply_json(choice)


def handle_planner(request: LLMRequest) -> OfflineReply:
    context = read_context(request)
    spec = PromptSpec.model_validate(context["spec"])
    max_steps: int = context["max_steps"]
    # The plan follows the needs the optimizer recorded in the spec; text detection is only a
    # fallback (deliverables excluded: "data model" in a deliverable is not a data request).
    recorded = {m for r in spec.requirements for m in _NEED_MARKER.findall(r)}
    intents = recorded or detect_intents(" ".join([spec.objective, *spec.requirements]))
    if spec.needs_knowledge_base:
        intents.add("knowledge")
    topic = truncate(spec.objective, 160)

    steps: list[PlanStep] = []
    if "knowledge" in intents:
        steps.append(
            PlanStep(
                id="knowledge_review",
                type=StepType.KNOWLEDGE,
                title="Review internal documentation",
                description=f"Internal rules and conventions for: {topic}",
                recommended_agent="rag",
                priority=1,
                success_criteria=["Relevant internal documents are identified", "Sources cited"],
            )
        )
    if "research" in intents:
        steps.append(
            PlanStep(
                id="context_research",
                type=StepType.RESEARCH,
                title="Research context and prior work",
                description=f"Gather facts, past tasks and options related to: {topic}",
                recommended_agent="research",
                priority=2,
                success_criteria=["Findings are backed by evidence"],
            )
        )
    if "data" in intents:
        steps.append(
            PlanStep(
                id="data_analysis",
                type=StepType.DATA,
                title="Analyse platform data",
                description=f"Compute the metrics needed to answer: {topic}",
                recommended_agent="data",
                priority=2,
                success_criteria=["Metrics are computed from platform data"],
            )
        )
    if "coding" in intents:
        steps.append(
            PlanStep(
                id="solution_design",
                type=StepType.CODING,
                title="Design the solution",
                description=f"Design the technical solution for: {topic}. "
                "Build on the outputs of the previous steps.",
                recommended_agent="coding",
                dependencies=[step.id for step in steps],
                priority=1,
                success_criteria=[
                    "Components, API endpoints and data model are specified",
                    "Risks and tests are listed",
                ],
            )
        )
    kept = steps[:max_steps]
    kept_ids = {step.id for step in kept}
    kept = [
        step.model_copy(update={"dependencies": [d for d in step.dependencies if d in kept_ids]})
        for step in kept
    ]
    plan = Plan(
        rationale=f"{len(kept)} step(s) derived from the needs detected in the specification: "
        f"{', '.join(sorted(intents)) or 'general analysis'}.",
        steps=kept,
    )
    return reply_json(plan)
